name: "TFE Infrastructure workflow"

on:
 workflow_dispatch:
 push:
   branches:
   - main
   paths:
   - terraform/**
 pull_request:
   branches:
   - main
   paths:
   - terraform/**
 
env:
 TF_LOG: INFO
 # Credentials for deployment to AWS
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 # S3 bucket for the Terraform state
 BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
 BUCKET_TF_STATE_KEY: ${{ secrets.BUCKET_TF_STATE_KEY }}
 
jobs:
 terraform:
   name: "ci"
   runs-on: ubuntu-latest
   defaults:
     run:
       shell: bash
       # We keep Terraform files in the terraform directory.
       working-directory: ./terraform
 
   steps:
     - name: Checkout the repository
       uses: actions/checkout@v3
 
     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v2
       with:
         terraform_version: 1.3.0
    
     - name: Terraform init
       id: init
       run: terraform init -backend-config="bucket=${BUCKET_TF_STATE}" -backend-config="key=${BUCKET_TF_STATE_KEY}"
 
     - name: Terraform format
       id: fmt
       run: terraform fmt -check